### ISSUE TITLE
Write trait does include write_buffered method

### ISSUE THREAD

**Issue by Soveu** [fanout/condure#1]
Hey, while scrolling through your code I noticed, that you provide your own `WriteVectored` trait, while the std `Write` does in fact provide `write_buffered` method
https://doc.rust-lang.org/std/io/trait.Write.html#method.write_vectored

**Comment by jkarneges** [comment]
I believe this was done because mio 0.6 doesn't implement `write_vectored` as part of the `Write` trait. Hopefully when we upgrade to mio 0.7 we can lose the custom trait.

**Comment by jkarneges** [comment]
We are now simply using the Write trait, after upgrading to mio 0.7.
