### ISSUE TITLE
Let's Encrypt SSL don't work?

### ISSUE THREAD

**Issue by tmikaeld** [fanout/condure#11]
I'm using Let's encrypt with pushpin on port 4430.

I've symlinked the certs to `/etc/pushpin/runner/certs/default_4430.key` and `/etc/pushpin/runner/certs/default_4430.crt` from `/etc/letsencrypt/live/domain.xyz/fullchain.pem` and `/etc/letsencrypt/live/domain.xyz/privkey.pem` and confirmed the files are symlinked.

But I get the error `ERR_SSL_UNRECOGNIZED_NAME_ALERT` in browser or `tlsv1 unrecognized name` in curl.
Tried to find information about condure, but none available.

I don't see any errors in either pushpin nor Condure logs.

Update: I've tried both with wildcard and without wildcard, result is the same.
Update2: Tried with just chain instead of fullchain, same result.

**Comment by tmikaeld** [comment]
Documentation missmatch, says `domain.xyz.crt` and `domain.xyz.key` would work, but only `_.domain.xyz.key` and `_.domain.xyz.crt` works and as to be chowned to the webserver user.

**Comment by jkarneges** [comment]
The `_.domain.xyz.crt` name format should only be needed for wildcard subdomains, and not for a single domain `domain.xyz`. Are you using wildcards?

**Comment by tmikaeld** [comment]
@jkarneges Yes, I'm using wildcard.

**Comment by jkarneges** [comment]
Thanks. Apparently that was undocumented. I've updated the docs.
